### ISSUE TITLE
design and implement user authorization

### ISSUE THREAD

**Issue by thiagomanel** [fogbow/arrebol#10]
as per title

**Comment by marcosnobrega** [comment]
The problem is to provide user authentication. Our solution does so and avoids middle-man/replay attacks (common attack in similar cases).

We require a secret to be shared between a user and the server. For example, sharing a password. This is to be done outside the protocol.

We do not require a HTTPS connections (to simplify arrebol deployment).

Our solution is to use a hash and a NONCE in every request.

The server should keep a local database with the registered users (user name and password) and a list of valid NONCE values, before every request the client should request a NONCE to the server, that generates and save the value in a list of valid NONCE values and then return it to the client. The NONCE is a value generated by the server that cannot be used in more than one request.

The user now do the request (GET, POST, DELETE a job) passing by the user name, NONCE value and a hash of the password + NONCE.

Once the server receives the request it locates the user by the user name, gets the password and create a hash of the password + NONCE and then compares it to the user's hash. If it matches, the server answers the request and remove the NONCE from list of valid NONCE values.

**Comment by marcosnobrega** [comment]
We have a few changes to do in the authorization method:
- use the public key instead of the password in the database;
- change user database to save the user name, public key and status (active, inactive);
- create an endpoint to register users, and new users are registered as inactive;
- new users need to be approved by an admin;
- the authentication hash should be the NONCE + user name encrypted using the user's private key;
- the server need to use the public key in the database to check the hash sent by the user.
